### ISSUE TITLE
A question about the list of models

### ISSUE THREAD

**Issue by aborruso** [angerman/llm-groq#14]
Hi @angerman and thank you for this plugin.

If I print the list of llm groq models I have

```
LLMGroq: groq-llama2
LLMGroq: groq-llama3
LLMGroq: groq-llama3-70b
LLMGroq: groq-llama3.1-8b
LLMGroq: groq-llama3.1-70b
LLMGroq: groq-llama3.1-405b
LLMGroq: groq-mixtral
LLMGroq: groq-gemma
LLMGroq: groq-gemma2
```

I know that in latest 0.6 plugin release I can use `llama-3.3-70b-versatile` via your groq plugin.  How to use it? Is it `groq-llama3-70b`?

Thank you

**Comment by aj47** [comment]
+1

**Comment by aj47** [comment]
fixed with `llm install llm-groq --upgrade`

**Comment by aborruso** [comment]
thank you @aj47 , it works
